import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Track every trade executed or imported from Hyperliquid
  trades: defineTable({
    symbol: v.string(),        // e.g., "HYPE", "BTC"
    side: v.string(),          // "buy" or "sell"
    entryPrice: v.number(),
    exitPrice: v.optional(v.number()),
    amount: v.number(),
    status: v.string(),        // "OPEN", "CLOSED", "CANCELLED"
    pnl: v.optional(v.number()),
    openedAt: v.number(),
    closedAt: v.optional(v.number()),
  }).index("by_status", ["status"]),

  // AI Signals generated by Kimi/Gemini
  signals: defineTable({
    symbol: v.string(),
    action: v.string(),        // "BUY", "SELL", "WAIT"
    reasoning: v.string(),     // The "why" from Kimi
    confidence: v.number(),
    processed: v.boolean(),
    timestamp: v.number(),
  }).index("by_symbol", ["symbol"]),

  // User/Bot configurations
  settings: defineTable({
    isAutoTrading: v.boolean(),
    maxLeverage: v.number(),
    stopLossPercent: v.number(),
    takeProfitPercent: v.number(),
    activeWallet: v.optional(v.string()),
    minBalanceThreshold: v.number(), // Bot stops if balance is below this
    allowedSymbols: v.array(v.string()), // e.g. ["BTC", "HYPE", "SOL", "ETH"]
    activeSymbol: v.string(), // The one we are currently hunting in
  }),
});
